title: Maxxwell Firth
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Maxxwell Firth
permalink: ':title'
# permalink: ':title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxxwell.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: markwf #if your site has a twitter account, enter it here

# Author Settings
author: Maxxwell Firth # add your name
author-img: maxxwell.png # add your photo
about-author: Jack of all trades, master of some. Operations & strategy professional. Tech startup guy. Content creator. # add description
social-twitter: markwf # add your Twitter handle
social-instagram: maxxwellfirth # add your Instagram handle
social-github: maxxwellfirth # add your Github handle
social-linkedin: maxxwell # add your Linkedin handle
social-email: maxx@maxxwell.co.uk # add your Email address

# Disqus
discus-identifier: markwf # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
